JuliaContainerization/Sandbox.jl

- Project.toml
We require a version of `UserNSSandbox_jll` that has the `--entrypoint` capability.
> Require a newer version of `UserNSSandbox_jll`

- src/Sandbox.jl
- test/Sandbox.jl
- need to launch processes in the background, so forward kwargs and don't call `success` in `run`
- `preferred_executor` behaved funnily when called 128 times in parallel, returning different executors, so put it behind a lock
> Changes for PkgEval

- src/Sandbox.jl
This allows you to customize the construction of the `SandboxExecutor`.
For example:
```julia
with_executor(DockerExecutor; privileges = :no_new_privileges) do exe
run(exe, config, `/bin/sh`)
end
```
> Allow the `with_executor` function to take keyword arguments, which it will forward to the `executor_type` constructor

- Artifacts.toml
- contrib/debootstrap_example.jl
- contrib/steal_docker_julia_alpine.jl
- src/Sandbox.jl
- test/Sandbox.jl
Also add a test to ensure that we can use `apt` and `curl` inside of the
debian rootfs (this isn't so much a sandbox thing as a "this is an
important usecase" thing)
> Add `debian_rootfs()`

- Artifacts.toml
- contrib/Project.toml
- contrib/docker_build_example/Dockerfile
- contrib/docker_build_example/build_docker_image.jl
- src/Docker.jl
- src/Sandbox.jl
Also add the `julia` and `python3` debgian rootfs as an example of how
to build something a little more chunky.
> Update contrib with a Dockerifle building example

- .github/workflows/ci.yml
A typo in the YAML file was causing the names of CI jobs to not include the boolean that indicates whether or not we are building the sandbox locally.
> CI: Fix the names of the CI jobs so that they include whether or not we are building the sandbox locally

- deps/userns_sandbox.c
- src/SandboxConfig.jl
- src/UserNamespaces.jl
- test/UserNamespaces.jl
This PR adds the optional `--tmpfs-size` command-line option to the user namespace sandbox. 
If the option is not provided, it falls back to the default value of `"1G"`.
> Add the optional `--tmpfs-size` command-line option to the user namespace sandbox

- src/UserNamespaces.jl
- src/utils.jl
If I understand correctly, one of the reasons that we require the Linux kernel version to be at least 3.18 is because 3.18 contains some security fixes for user namespaces.
E.g. from https://sylabs.io/guides/3.5/admin-guide/user_namespace.html:
> To allow unprivileged creation of user namespaces a kernel >=3.8 is required, with >=3.18 being recommended due to security fixes for user namespaces (3.18 also adds OverlayFS support which is used by Singularity).
Since the security fixes are not available before 3.18, I think we should err on the side of caution.
Therefore, if for some reason we are not able to parse the kernel version, we should not assume that the kernel version is >= 3.18, because if we make that assumption and it is incorrect, we would be using user namespaces with a kernel …
> If the Linux kernel version cannot be parsed, do not assume it is >= 3.18

- src/Sandbox.jl
- test/UserNamespaces.jl
Using the `maxlog=1` kwarg accomplishes the same thing without requiring us to manage a global variable.
For example:
```julia
julia> function warn_priviledged()
@info("Running privileged container via `sudo`, may ask for your password:", maxlog=1)
return nothing
end
warn_priviledged (generic function with 1 method)
julia> warn_priviledged()
[ Info: Running privileged container via `sudo`, may ask for your password:
julia> warn_priviledged()
julia> warn_priviledged()
julia> warn_priviledged()
```
> For the `warn_priviledged` function, use `maxlog=1` instead of using a global variable

- Project.toml
- src/Docker.jl
Some systems (e.g. macOS) ship by default with a BSD `tar` that does not support the `--owner` and `--group` command-line options.
This PR adds Tar_jll.jl as a dependency and uses it to provide a GNU `tar` so that we do not have to rely on the system `tar`.
If Tar_jll is not supported on the platform, we fall back to the system `tar`.
> Use Tar_jll.jl to provide a GNU tar binary (instead of relying on the system tar)

- src/binfmt_misc.jl
Users will probably wonder why they are being asked for their `sudo` password (especially if they want to use the unprivileged user namespaces executor), so we should always show the `@info` message explaining why, even if `verbose` is `false`.
> When registering binfmt_misc entries, print an `@info` message about sudo even if `verbose` is `false`

- deps/userns_sandbox.c
- src/Docker.jl
- src/SandboxConfig.jl
- src/UserNamespaces.jl
- test/Sandbox.jl
- test/SandboxConfig.jl
This allows us to launch sandboxes with a deterministic hostname, if we so desire to.  Useful for things like fully reproducible builds, etc...
Closes https://github.com/staticfloat/Sandbox.jl/issues/64
> Add `hostname` option to `SandboxConfig`

- src/UserNamespaces.jl
Fixes https://github.com/JuliaCI/PkgEval.jl/issues/98, where every package depending on Arrow.jl fails to clean up.
```
┌ Error: Unexpected error while cleaning up process
│   exception =
│    IOError: stat("/tmp/jl_lXgiOx/upper/rootfs/home/pkgeval/.julia/packages/Arrow/PQ5Mm/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github/pkgs/Arrow.jl/.github"): too many symbolic links encountered (ELOOP)
│ …
```
> Don't recurse into links when setting permissions.

- Project.toml
- src/Docker.jl
This has the new `JLLWrappers`-based interface which provides the function
`is_available` to query availability and also supports more platforms than the
build of v1.32.
> Allow using `Tar_jll` v1.34

- src/UserNamespaces.jl
In #75 it turned out that the `overlay` module is always necessary, this PR
makes the warning more explicit about this point.
Fix #75.
> [UserNamespaces] Make it clearer that the `overlay` module is needed

- Project.toml
- deps/build_local_sandbox.jl
- deps/userns_sandbox.c
- test/Project.toml
- test/runtests.jl
This is needed for `gpg-agent`, and all users of `libgcrypt`,
apparently.
X-ref: https://github.com/gpg/libgcrypt/blob/9c42db0b379c277ee976fcc696e84e31863a85a8/random/random-csprng.c#L1205-L1210
> Bind-mount `/dev/random` in as well

- src/Docker.jl
- test/Docker.jl
On aarch64 platforms tests would try to pull the Julia alpine image for that
platform, but there is only for `x86_64`.  With this change we can specify the
platform and force `linux/amd64` for this image.
With this change some tests pass on the M1, but they eventually fail because
#51 forced `Tar_jll` 1.32 which isn't available for this platform.
> [Docker] Add platform argument to `pull_docker_image`

- Artifacts.toml
- deps/userns_sandbox.c
- src/Sandbox.jl
- test/UserNamespaces.jl
We want to be able to send things like  `SIGTERM` to the process we
started in the sandbox, and so we forward many useful signals through.
If our child then dies with a signal, we find a way to pass this
information back up to the parent.
Note that I am not totally happy with the implementation here, as if a
child exits with a status of `143`, then the sandbox will assume that it
was actually a `SIGTERM`.  We should probably create some kind of
out-of-band information that says that a child signaled, or we should
somehow fix the fact that PID 1 in a namespace can't SIGTERM itself.
> Signal handling

- Project.toml
This new version required for recent signal handling features.
> Bump required version of UserNSSandbox_jll

- deps/userns_sandbox.c
- test/Nesting.jl
- test/nested/nested_child.jl
Fixes https://github.com/staticfloat/Sandbox.jl/issues/98, supersedes https://github.com/staticfloat/Sandbox.jl/pull/97.
> Fix sysfs mount.

- deps/userns_sandbox.c
That is more likely to be correct in the case of a nested sandboxing.
> Read from `/proc/self/mounts`

- Project.toml
- src/Sandbox.jl
`main` (da1ccc1017fac4a2a42de98c30a29e337fb06e74):
```console
% julia +1.7 --startup-file=no --project=/tmp -q
julia> using Sandbox; @time @eval Sandbox.select_executor(false);
2.771236 seconds (10.20 M allocations: 540.632 MiB, 7.27% gc time, 100.00% compilation time)
% julia +1.8 --startup-file=no --project=/tmp -q
julia> using Sandbox; @time @eval Sandbox.select_executor(false);
2.598736 seconds (8.77 M allocations: 448.371 MiB, 7.11% gc time, 99.77% compilation time)
% julia +1.9 --startup-file=no --project=/tmp -q
julia> using Sandbox; @time @eval Sandbox.select_executor(false);
2.492451 seconds (4.97 M allocations: 332.907 MiB, 6.76% gc time, 99.71% compilation time)
```
This PR:
```console
% julia +1.7 --startup-file=no --project=/tmp -q
julia> using Sandbox; @time @eval …
```
> Add a couple of precompilation statements

- deps/userns_sandbox.c
The current sandbox code has a race condition. If the child exits before the sigwait signal mask is setup, we will hang forever waiting for a signal. This has been observed in practice in Yggdrasil. I don't know that the sigwait here is supposed to do - plain waitpid should be fine, so try removing it to see if everything works.
If the sigwait does turn out to be necessary, we should be able to fix this by moving the signal mask setup to above the fork instead.
> Fix race condition in sandbox

- deps/userns_common.c
Notably, adding SIGQUIT, but also the TTY signals (in case we ended up as a tty owner), and sorting the list by signal number
> forward all commonly user-generated signals

- Project.toml
This gets us the `OverlayedReadOnly` support
> Bump UserNSSandbox minimum version

- src/Docker.jl
- src/Sandbox.jl
- src/UserNamespaces.jl
- test/UserNamespaces.jl
If specified they will override the global stdio config. A primary motivation is to pass non-stdio fds, cf
https://github.com/JuliaLang/julia/commit/79a5ccd237dbed05dd8f85c4e948656ebf76eb48.
> Allow specifying `CmdRedirect` as user command
